backpacks:
  give-recipes-on-obtain: true
  max-attached-backpacks: 6
  enable-crafting-addon: true
  enable-jukebox-addon: true
  enable-quiver-addon: true
  enable-enchant-addon: true
  enable-glider-addon: true
  gui:
    play-sound-on-open: true
    play-sound-on-close: true
  quiver:
    auto-fill-bow: true
    check-inventory-first: true
